// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations.HomeApp
{
    [DbContext(typeof(HomeAppContext))]
    [Migration("20250920091114_Init_HomeApp")]
    partial class Init_HomeApp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Budgets.Budget", b =>
                {
                    b.Property<int>("BudgetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("budget_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BudgetId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("BudgetId")
                        .HasName("pk_budgets");

                    b.HasIndex("PersonId", "Year")
                        .IsUnique()
                        .HasDatabaseName("ix_budgets_person_id_year");

                    b.ToTable("Budgets", "public");
                });

            modelBuilder.Entity("Domain.Entities.Budgets.BudgetCell", b =>
                {
                    b.Property<int>("BudgetCellId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("budget_cell_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BudgetCellId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<int>("BudgetRowId")
                        .HasColumnType("integer")
                        .HasColumnName("budget_row_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("BudgetCellId")
                        .HasName("pk_budget_cells");

                    b.HasIndex("BudgetRowId")
                        .HasDatabaseName("ix_budget_cells_budget_row_id");

                    b.HasIndex("BudgetRowId", "Month")
                        .IsUnique()
                        .HasDatabaseName("ix_budget_cells_budget_row_id_month");

                    b.ToTable("BudgetCells", "public", t =>
                        {
                            t.HasCheckConstraint("ck_budgetcell_month", "month BETWEEN 1 AND 12");
                        });
                });

            modelBuilder.Entity("Domain.Entities.Budgets.BudgetGroup", b =>
                {
                    b.Property<int>("BudgetGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("budget_group_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BudgetGroupId"));

                    b.Property<int>("BudgetGroupType")
                        .HasColumnType("integer")
                        .HasColumnName("budget_group_type");

                    b.Property<int>("BudgetId")
                        .HasColumnType("integer")
                        .HasColumnName("budget_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("BudgetGroupId")
                        .HasName("pk_budget_groups");

                    b.HasIndex("BudgetId")
                        .HasDatabaseName("ix_budget_groups_budget_id");

                    b.HasIndex("BudgetId", "Index")
                        .IsUnique()
                        .HasDatabaseName("ix_budget_groups_budget_id_index");

                    b.ToTable("BudgetGroups", "public");
                });

            modelBuilder.Entity("Domain.Entities.Budgets.BudgetRow", b =>
                {
                    b.Property<int>("BudgetRowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("budget_row_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BudgetRowId"));

                    b.Property<int>("BudgetGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("budget_group_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("BudgetRowId")
                        .HasName("pk_budget_rows");

                    b.HasIndex("BudgetGroupId")
                        .HasDatabaseName("ix_budget_rows_budget_group_id");

                    b.HasIndex("BudgetGroupId", "Index")
                        .IsUnique()
                        .HasDatabaseName("ix_budget_rows_budget_group_id_index");

                    b.ToTable("BudgetRows", "public");
                });

            modelBuilder.Entity("Domain.Entities.People.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("person_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PersonId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("username");

                    b.HasKey("PersonId")
                        .HasName("pk_people");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_people_email");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_people_user_id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_people_username");

                    b.ToTable("People", "public");
                });

            modelBuilder.Entity("Domain.Entities.Todos.Todo", b =>
                {
                    b.Property<int>("TodoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("todo_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TodoId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<bool>("Done")
                        .HasColumnType("boolean")
                        .HasColumnName("done");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("TodoId")
                        .HasName("pk_todos");

                    b.HasIndex("Done")
                        .HasDatabaseName("ix_todos_done");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_todos_name");

                    b.HasIndex("Priority")
                        .HasDatabaseName("ix_todos_priority");

                    b.HasIndex("TodoId")
                        .IsUnique()
                        .HasDatabaseName("ix_todos_todo_id");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_todos_updated_at");

                    b.ToTable("Todos", "public");
                });

            modelBuilder.Entity("Domain.Entities.Todos.TodoGroup", b =>
                {
                    b.Property<int>("TodoGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("todo_group_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TodoGroupId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("TodoGroupId")
                        .HasName("pk_todo_groups");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_todo_groups_name");

                    b.HasIndex("TodoGroupId")
                        .IsUnique()
                        .HasDatabaseName("ix_todo_groups_todo_group_id");

                    b.ToTable("TodoGroups", "public");
                });

            modelBuilder.Entity("Domain.Entities.Todos.TodoGroupTodo", b =>
                {
                    b.Property<int>("TodoGroupTodoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("todo_group_todo_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TodoGroupTodoId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<int>("TodoGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("todo_group_id");

                    b.Property<int>("TodoId")
                        .HasColumnType("integer")
                        .HasColumnName("todo_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("TodoGroupTodoId")
                        .HasName("pk_todo_group_todos");

                    b.HasIndex("TodoGroupId")
                        .HasDatabaseName("ix_todo_group_todos_todo_group_id");

                    b.HasIndex("TodoId")
                        .IsUnique()
                        .HasDatabaseName("ix_todo_group_todos_todo_id");

                    b.ToTable("TodoGroupTodos", "public");
                });

            modelBuilder.Entity("Domain.Entities.Todos.TodoPerson", b =>
                {
                    b.Property<int>("TodoPersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("todo_person_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TodoPersonId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<int>("TodoId")
                        .HasColumnType("integer")
                        .HasColumnName("todo_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("TodoPersonId")
                        .HasName("pk_todo_people");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_todo_people_person_id");

                    b.HasIndex("TodoId")
                        .HasDatabaseName("ix_todo_people_todo_id");

                    b.ToTable("TodoPeople", "public");
                });

            modelBuilder.Entity("Domain.Entities.Budgets.Budget", b =>
                {
                    b.HasOne("Domain.Entities.People.Person", "Person")
                        .WithMany("Budgets")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_budgets_people_person_id");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Domain.Entities.Budgets.BudgetCell", b =>
                {
                    b.HasOne("Domain.Entities.Budgets.BudgetRow", "BudgetRow")
                        .WithMany("Cells")
                        .HasForeignKey("BudgetRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_budget_cells_budget_rows_budget_row_id");

                    b.Navigation("BudgetRow");
                });

            modelBuilder.Entity("Domain.Entities.Budgets.BudgetGroup", b =>
                {
                    b.HasOne("Domain.Entities.Budgets.Budget", "Budget")
                        .WithMany("BudgetGroups")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_budget_groups_budgets_budget_id");

                    b.Navigation("Budget");
                });

            modelBuilder.Entity("Domain.Entities.Budgets.BudgetRow", b =>
                {
                    b.HasOne("Domain.Entities.Budgets.BudgetGroup", "Group")
                        .WithMany("BudgetRows")
                        .HasForeignKey("BudgetGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_budget_rows_budget_groups_budget_group_id");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Domain.Entities.Todos.TodoGroupTodo", b =>
                {
                    b.HasOne("Domain.Entities.Todos.TodoGroup", "TodoGroup")
                        .WithMany("TodoGroupTodos")
                        .HasForeignKey("TodoGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_todo_group_todos_todo_groups_todo_group_id");

                    b.HasOne("Domain.Entities.Todos.Todo", "Todo")
                        .WithOne("TodoGroupTodo")
                        .HasForeignKey("Domain.Entities.Todos.TodoGroupTodo", "TodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_todo_group_todos_todos_todo_id");

                    b.Navigation("Todo");

                    b.Navigation("TodoGroup");
                });

            modelBuilder.Entity("Domain.Entities.Todos.TodoPerson", b =>
                {
                    b.HasOne("Domain.Entities.People.Person", "Person")
                        .WithMany("TodoPeople")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_todo_people_people_person_id");

                    b.HasOne("Domain.Entities.Todos.Todo", "Todo")
                        .WithMany("TodoPeople")
                        .HasForeignKey("TodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_todo_people_todos_todo_id");

                    b.Navigation("Person");

                    b.Navigation("Todo");
                });

            modelBuilder.Entity("Domain.Entities.Budgets.Budget", b =>
                {
                    b.Navigation("BudgetGroups");
                });

            modelBuilder.Entity("Domain.Entities.Budgets.BudgetGroup", b =>
                {
                    b.Navigation("BudgetRows");
                });

            modelBuilder.Entity("Domain.Entities.Budgets.BudgetRow", b =>
                {
                    b.Navigation("Cells");
                });

            modelBuilder.Entity("Domain.Entities.People.Person", b =>
                {
                    b.Navigation("Budgets");

                    b.Navigation("TodoPeople");
                });

            modelBuilder.Entity("Domain.Entities.Todos.Todo", b =>
                {
                    b.Navigation("TodoGroupTodo")
                        .IsRequired();

                    b.Navigation("TodoPeople");
                });

            modelBuilder.Entity("Domain.Entities.Todos.TodoGroup", b =>
                {
                    b.Navigation("TodoGroupTodos");
                });
#pragma warning restore 612, 618
        }
    }
}
