// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations.HomeApp
{
    [DbContext(typeof(HomeAppContext))]
    [Migration("20251229183920_updatedArticleRecipeDb")]
    partial class updatedArticleRecipeDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Articles.Allergen", b =>
                {
                    b.Property<int>("AllergenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("allergen_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AllergenId"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("AllergenId")
                        .HasName("pk_allergens");

                    b.HasIndex("Code")
                        .HasDatabaseName("ix_allergens_code");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_allergens_name");

                    b.ToTable("allergens", "article");
                });

            modelBuilder.Entity("Domain.Entities.Articles.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("article_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArticleId"));

                    b.Property<int?>("ArticleCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("article_category_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("ArticleId")
                        .HasName("pk_articles");

                    b.HasIndex("ArticleCategoryId")
                        .HasDatabaseName("ix_articles_article_category_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_articles_name");

                    b.ToTable("articles", "article");
                });

            modelBuilder.Entity("Domain.Entities.Articles.ArticleAllergen", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("integer")
                        .HasColumnName("article_id")
                        .HasColumnOrder(0);

                    b.Property<int>("AllergenId")
                        .HasColumnType("integer")
                        .HasColumnName("allergen_id")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(2)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(3);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(4);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(5);

                    b.HasKey("ArticleId", "AllergenId")
                        .HasName("pk_article_allergens");

                    b.HasIndex("AllergenId")
                        .HasDatabaseName("ix_article_allergens_allergen_id");

                    b.HasIndex("ArticleId")
                        .HasDatabaseName("ix_article_allergens_article_id");

                    b.ToTable("article_allergens", "article");
                });

            modelBuilder.Entity("Domain.Entities.Articles.ArticleCategory", b =>
                {
                    b.Property<int>("ArticleCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("article_category_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArticleCategoryId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_category_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("ArticleCategoryId")
                        .HasName("pk_article_categories");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_article_categories_name");

                    b.HasIndex("ParentCategoryId")
                        .HasDatabaseName("ix_article_categories_parent_category_id");

                    b.ToTable("article_categories", "article");
                });

            modelBuilder.Entity("Domain.Entities.Articles.ArticleNutrition", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("integer")
                        .HasColumnName("article_id")
                        .HasColumnOrder(0);

                    b.Property<decimal?>("CaloriesKcalPer100g")
                        .HasColumnType("numeric")
                        .HasColumnName("calories_kcal_per_100g");

                    b.Property<decimal?>("CarbsGPer100g")
                        .HasColumnType("numeric")
                        .HasColumnName("carbs_g_per_100g");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<decimal?>("FatGPer100g")
                        .HasColumnType("numeric")
                        .HasColumnName("fat_g_per_100g");

                    b.Property<decimal?>("FiberGPer100g")
                        .HasColumnType("numeric")
                        .HasColumnName("fiber_g_per_100g");

                    b.Property<string>("LastSource")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_source");

                    b.Property<decimal?>("ProteinGPer100g")
                        .HasColumnType("numeric")
                        .HasColumnName("protein_g_per_100g");

                    b.Property<decimal?>("SaltGPer100g")
                        .HasColumnType("numeric")
                        .HasColumnName("salt_g_per_100g");

                    b.Property<decimal?>("SaturatedFatGPer100g")
                        .HasColumnType("numeric")
                        .HasColumnName("saturated_fat_g_per_100g");

                    b.Property<decimal?>("SugarGPer100g")
                        .HasColumnType("numeric")
                        .HasColumnName("sugar_g_per_100g");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("ArticleId")
                        .HasName("pk_article_nutritions");

                    b.ToTable("article_nutritions", "article");
                });

            modelBuilder.Entity("Domain.Entities.Articles.ArticlePrice", b =>
                {
                    b.Property<int>("ArticlePriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("article_price_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArticlePriceId"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("integer")
                        .HasColumnName("article_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("EUR")
                        .HasColumnName("currency");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<int>("StoreId")
                        .HasColumnType("integer")
                        .HasColumnName("store_id");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer")
                        .HasColumnName("unit_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("ArticlePriceId")
                        .HasName("pk_article_prices");

                    b.HasIndex("ArticleId")
                        .HasDatabaseName("ix_article_prices_article_id");

                    b.HasIndex("StoreId")
                        .HasDatabaseName("ix_article_prices_store_id");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_article_prices_unit_id");

                    b.HasIndex("ArticleId", "StoreId", "UnitId", "ValidFrom")
                        .IsUnique()
                        .HasDatabaseName("ix_article_prices_article_id_store_id_unit_id_valid_from");

                    b.ToTable("article_prices", "article");
                });

            modelBuilder.Entity("Domain.Entities.Articles.Store", b =>
                {
                    b.Property<int>("StoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("store_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StoreId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("website_url");

                    b.HasKey("StoreId")
                        .HasName("pk_stores");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_stores_name");

                    b.ToTable("stores", "article");
                });

            modelBuilder.Entity("Domain.Entities.Articles.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("unit_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UnitId"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("abbreviation");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("UnitId")
                        .HasName("pk_units");

                    b.HasIndex("Abbreviation")
                        .IsUnique()
                        .HasDatabaseName("ix_units_abbreviation");

                    b.ToTable("units", "article");
                });

            modelBuilder.Entity("Domain.Entities.Budgets.Budget", b =>
                {
                    b.Property<int>("BudgetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("budget_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BudgetId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("BudgetId")
                        .HasName("pk_budgets");

                    b.HasIndex("PersonId", "Year")
                        .IsUnique()
                        .HasDatabaseName("ix_budgets_person_id_year");

                    b.ToTable("budgets", "budget");
                });

            modelBuilder.Entity("Domain.Entities.Budgets.BudgetCell", b =>
                {
                    b.Property<int>("BudgetCellId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("budget_cell_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BudgetCellId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<int>("BudgetRowId")
                        .HasColumnType("integer")
                        .HasColumnName("budget_row_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("BudgetCellId")
                        .HasName("pk_budget_cells");

                    b.HasIndex("BudgetRowId")
                        .HasDatabaseName("ix_budget_cells_budget_row_id");

                    b.HasIndex("BudgetRowId", "Month")
                        .IsUnique()
                        .HasDatabaseName("ix_budget_cells_budget_row_id_month");

                    b.ToTable("budget_cells", "budget", t =>
                        {
                            t.HasCheckConstraint("ck_budgetcell_month", "month BETWEEN 1 AND 12");
                        });
                });

            modelBuilder.Entity("Domain.Entities.Budgets.BudgetGroup", b =>
                {
                    b.Property<int>("BudgetGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("budget_group_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BudgetGroupId"));

                    b.Property<int>("BudgetGroupType")
                        .HasColumnType("integer")
                        .HasColumnName("budget_group_type");

                    b.Property<int>("BudgetId")
                        .HasColumnType("integer")
                        .HasColumnName("budget_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("BudgetGroupId")
                        .HasName("pk_budget_groups");

                    b.HasIndex("BudgetId")
                        .HasDatabaseName("ix_budget_groups_budget_id");

                    b.HasIndex("BudgetId", "Index")
                        .IsUnique()
                        .HasDatabaseName("ix_budget_groups_budget_id_index");

                    b.ToTable("budget_groups", "budget");
                });

            modelBuilder.Entity("Domain.Entities.Budgets.BudgetRow", b =>
                {
                    b.Property<int>("BudgetRowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("budget_row_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BudgetRowId"));

                    b.Property<int>("BudgetGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("budget_group_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("BudgetRowId")
                        .HasName("pk_budget_rows");

                    b.HasIndex("BudgetGroupId")
                        .HasDatabaseName("ix_budget_rows_budget_group_id");

                    b.HasIndex("BudgetGroupId", "Index")
                        .IsUnique()
                        .HasDatabaseName("ix_budget_rows_budget_group_id_index");

                    b.ToTable("budget_rows", "budget");
                });

            modelBuilder.Entity("Domain.Entities.People.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("person_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PersonId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("username");

                    b.HasKey("PersonId")
                        .HasName("pk_people");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_people_email");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_people_user_id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_people_username");

                    b.ToTable("people", "people");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Favorite", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id")
                        .HasColumnOrder(0);

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(2)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(3);

                    b.Property<int?>("PersonId1")
                        .HasColumnType("integer")
                        .HasColumnName("person_id1");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(4);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(5);

                    b.HasKey("PersonId", "RecipeId")
                        .HasName("pk_recipe_favorites");

                    b.HasIndex("PersonId1")
                        .HasDatabaseName("ix_recipe_favorites_person_id1");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("ix_recipe_favorites_recipe_id");

                    b.ToTable("recipe_favorites", "recipe");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.PopularSearchQuery", b =>
                {
                    b.Property<int>("QueryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("query_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QueryId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("LastSearchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_searched_at");

                    b.Property<string>("QueryText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("query_text");

                    b.Property<int>("SearchCount")
                        .HasColumnType("integer")
                        .HasColumnName("search_count");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("QueryId")
                        .HasName("pk_popular_search_queries");

                    b.HasIndex("QueryText")
                        .IsUnique()
                        .HasDatabaseName("ix_popular_search_queries_query_text");

                    b.ToTable("popular_search_queries", "recipe");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecipeId"));

                    b.Property<int?>("CookTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("cook_time_minutes");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_public");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<int?>("PersonId1")
                        .HasColumnType("integer")
                        .HasColumnName("person_id1");

                    b.Property<int?>("PrepTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("prep_time_minutes");

                    b.Property<decimal?>("Servings")
                        .HasColumnType("numeric")
                        .HasColumnName("servings");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("RecipeId")
                        .HasName("pk_recipes");

                    b.HasIndex("IsPublic")
                        .HasDatabaseName("ix_recipes_is_public");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_recipes_person_id");

                    b.HasIndex("PersonId1")
                        .HasDatabaseName("ix_recipes_person_id1");

                    b.ToTable("recipes", "recipe");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.RecipeCategory", b =>
                {
                    b.Property<int>("RecipeCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("recipe_category_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecipeCategoryId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("RecipeCategoryId")
                        .HasName("pk_recipe_categories");

                    b.HasIndex("RecipeId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_recipe_categories_recipe_id_name");

                    b.ToTable("recipe_categories", "recipe");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.RecipeComment", b =>
                {
                    b.Property<int>("RecipeCommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("recipe_comment_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecipeCommentId"));

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comment_text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<int?>("PersonId1")
                        .HasColumnType("integer")
                        .HasColumnName("person_id1");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("RecipeCommentId")
                        .HasName("pk_recipe_comments");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_recipe_comments_person_id");

                    b.HasIndex("PersonId1")
                        .HasDatabaseName("ix_recipe_comments_person_id1");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("ix_recipe_comments_recipe_id");

                    b.ToTable("recipe_comments", "recipe");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.RecipeImage", b =>
                {
                    b.Property<int>("RecipeImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("recipe_image_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecipeImageId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("RecipeImageId")
                        .HasName("pk_recipe_images");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("ix_recipe_images_recipe_id");

                    b.ToTable("recipe_images", "recipe");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.RecipeIngredient", b =>
                {
                    b.Property<int>("RecipeIngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("recipe_ingredient_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecipeIngredientId"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("integer")
                        .HasColumnName("article_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("note");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<int?>("UnitId")
                        .HasColumnType("integer")
                        .HasColumnName("unit_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("RecipeIngredientId")
                        .HasName("pk_recipe_ingredients");

                    b.HasIndex("ArticleId")
                        .HasDatabaseName("ix_recipe_ingredients_article_id");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("ix_recipe_ingredients_recipe_id");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_recipe_ingredients_unit_id");

                    b.HasIndex("RecipeId", "SortOrder")
                        .IsUnique()
                        .HasDatabaseName("ix_recipe_ingredients_recipe_id_sort_order");

                    b.ToTable("recipe_ingredients", "recipe");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.RecipeRating", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id")
                        .HasColumnOrder(0);

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(2)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(3);

                    b.Property<int?>("PersonId1")
                        .HasColumnType("integer")
                        .HasColumnName("person_id1");

                    b.Property<DateTime>("RatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rated_at");

                    b.Property<short>("Rating")
                        .HasColumnType("smallint")
                        .HasColumnName("rating");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(4);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(5);

                    b.HasKey("RecipeId", "PersonId")
                        .HasName("pk_recipe_ratings");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_recipe_ratings_person_id");

                    b.HasIndex("PersonId1")
                        .HasDatabaseName("ix_recipe_ratings_person_id1");

                    b.ToTable("recipe_ratings", "recipe");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.RecipeSearchIndex", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id")
                        .HasColumnOrder(0);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("LastIndexedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_indexed_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("RecipeId")
                        .HasName("pk_recipe_search_index");

                    b.ToTable("recipe_search_index", "recipe");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.RecipeStep", b =>
                {
                    b.Property<int>("RecipeStepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("recipe_step_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecipeStepId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instruction");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id");

                    b.Property<int>("StepNumber")
                        .HasColumnType("integer")
                        .HasColumnName("step_number");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("RecipeStepId")
                        .HasName("pk_recipe_steps");

                    b.HasIndex("RecipeId", "StepNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_recipe_steps_recipe_id_step_number");

                    b.ToTable("recipe_steps", "recipe");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.RecipeTag", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id")
                        .HasColumnOrder(0);

                    b.Property<int>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("tag_id")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(2)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(3);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(4);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(5);

                    b.HasKey("RecipeId", "TagId")
                        .HasName("pk_recipe_tags");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_recipe_tags_tag_id");

                    b.ToTable("recipe_tags", "recipe");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tag_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TagId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("TagId")
                        .HasName("pk_tags");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_name");

                    b.ToTable("tags", "recipe");
                });

            modelBuilder.Entity("Domain.Entities.Todos.Todo", b =>
                {
                    b.Property<int>("TodoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("todo_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TodoId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<bool>("Done")
                        .HasColumnType("boolean")
                        .HasColumnName("done");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("TodoId")
                        .HasName("pk_todos");

                    b.HasIndex("Done")
                        .HasDatabaseName("ix_todos_done");

                    b.HasIndex("Priority")
                        .HasDatabaseName("ix_todos_priority");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_todos_title");

                    b.HasIndex("TodoId")
                        .IsUnique()
                        .HasDatabaseName("ix_todos_todo_id");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_todos_updated_at");

                    b.ToTable("todos", "todo");
                });

            modelBuilder.Entity("Domain.Entities.Todos.TodoGroup", b =>
                {
                    b.Property<int>("TodoGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("todo_group_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TodoGroupId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("TodoGroupId")
                        .HasName("pk_todo_groups");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_todo_groups_title");

                    b.HasIndex("TodoGroupId")
                        .IsUnique()
                        .HasDatabaseName("ix_todo_groups_todo_group_id");

                    b.ToTable("todo_groups", "todo");
                });

            modelBuilder.Entity("Domain.Entities.Todos.TodoGroupTodo", b =>
                {
                    b.Property<int>("TodoGroupTodoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("todo_group_todo_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TodoGroupTodoId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<int>("TodoGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("todo_group_id");

                    b.Property<int>("TodoId")
                        .HasColumnType("integer")
                        .HasColumnName("todo_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("TodoGroupTodoId")
                        .HasName("pk_todo_group_todos");

                    b.HasIndex("TodoGroupId")
                        .HasDatabaseName("ix_todo_group_todos_todo_group_id");

                    b.HasIndex("TodoId")
                        .IsUnique()
                        .HasDatabaseName("ix_todo_group_todos_todo_id");

                    b.ToTable("todo_group_todos", "todo");
                });

            modelBuilder.Entity("Domain.Entities.Todos.TodoPerson", b =>
                {
                    b.Property<int>("TodoPersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("todo_person_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TodoPersonId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<int>("TodoId")
                        .HasColumnType("integer")
                        .HasColumnName("todo_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("TodoPersonId")
                        .HasName("pk_todo_people");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_todo_people_person_id");

                    b.HasIndex("TodoId")
                        .HasDatabaseName("ix_todo_people_todo_id");

                    b.ToTable("todo_people", "todo");
                });

            modelBuilder.Entity("Domain.Entities.Articles.Article", b =>
                {
                    b.HasOne("Domain.Entities.Articles.ArticleCategory", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("ArticleCategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_articles_article_categories_article_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Entities.Articles.ArticleAllergen", b =>
                {
                    b.HasOne("Domain.Entities.Articles.Allergen", "Allergen")
                        .WithMany("ArticleAllergens")
                        .HasForeignKey("AllergenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_article_allergens_allergens_allergen_id");

                    b.HasOne("Domain.Entities.Articles.Article", "Article")
                        .WithMany("ArticleAllergens")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_article_allergens_articles_article_id");

                    b.Navigation("Allergen");

                    b.Navigation("Article");
                });

            modelBuilder.Entity("Domain.Entities.Articles.ArticleCategory", b =>
                {
                    b.HasOne("Domain.Entities.Articles.ArticleCategory", "ParentCategory")
                        .WithMany("Children")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_article_categories_article_categories_parent_category_id");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Domain.Entities.Articles.ArticleNutrition", b =>
                {
                    b.HasOne("Domain.Entities.Articles.Article", "Article")
                        .WithOne("ArticleNutrition")
                        .HasForeignKey("Domain.Entities.Articles.ArticleNutrition", "ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_article_nutritions_articles_article_id");

                    b.Navigation("Article");
                });

            modelBuilder.Entity("Domain.Entities.Articles.ArticlePrice", b =>
                {
                    b.HasOne("Domain.Entities.Articles.Article", "Article")
                        .WithMany("ArticlePrices")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_article_prices_articles_article_id");

                    b.HasOne("Domain.Entities.Articles.Store", "Store")
                        .WithMany("ArticlePrices")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_article_prices_stores_store_id");

                    b.HasOne("Domain.Entities.Articles.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_article_prices_units_unit_id");

                    b.Navigation("Article");

                    b.Navigation("Store");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Domain.Entities.Budgets.Budget", b =>
                {
                    b.HasOne("Domain.Entities.People.Person", "Person")
                        .WithMany("Budgets")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_budgets_people_person_id");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Domain.Entities.Budgets.BudgetCell", b =>
                {
                    b.HasOne("Domain.Entities.Budgets.BudgetRow", "BudgetRow")
                        .WithMany("BudgetCells")
                        .HasForeignKey("BudgetRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_budget_cells_budget_rows_budget_row_id");

                    b.Navigation("BudgetRow");
                });

            modelBuilder.Entity("Domain.Entities.Budgets.BudgetGroup", b =>
                {
                    b.HasOne("Domain.Entities.Budgets.Budget", "Budget")
                        .WithMany("BudgetGroups")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_budget_groups_budgets_budget_id");

                    b.Navigation("Budget");
                });

            modelBuilder.Entity("Domain.Entities.Budgets.BudgetRow", b =>
                {
                    b.HasOne("Domain.Entities.Budgets.BudgetGroup", "BudgetGroup")
                        .WithMany("BudgetRows")
                        .HasForeignKey("BudgetGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_budget_rows_budget_groups_budget_group_id");

                    b.Navigation("BudgetGroup");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Favorite", b =>
                {
                    b.HasOne("Domain.Entities.People.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_favorites_people_person_id");

                    b.HasOne("Domain.Entities.People.Person", null)
                        .WithMany("Favorites")
                        .HasForeignKey("PersonId1")
                        .HasConstraintName("fk_recipe_favorites_people_person_id1");

                    b.HasOne("Domain.Entities.Recipes.Recipe", "Recipe")
                        .WithMany("Favorites")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_favorites_recipes_recipe_id");

                    b.Navigation("Person");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Recipe", b =>
                {
                    b.HasOne("Domain.Entities.People.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipes_people_person_id");

                    b.HasOne("Domain.Entities.People.Person", null)
                        .WithMany("Recipes")
                        .HasForeignKey("PersonId1")
                        .HasConstraintName("fk_recipes_people_person_id1");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.RecipeCategory", b =>
                {
                    b.HasOne("Domain.Entities.Recipes.Recipe", "Recipe")
                        .WithMany("RecipeCategories")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_categories_recipes_recipe_id");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.RecipeComment", b =>
                {
                    b.HasOne("Domain.Entities.People.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_comments_people_person_id");

                    b.HasOne("Domain.Entities.People.Person", null)
                        .WithMany("RecipeComments")
                        .HasForeignKey("PersonId1")
                        .HasConstraintName("fk_recipe_comments_people_person_id1");

                    b.HasOne("Domain.Entities.Recipes.Recipe", "Recipe")
                        .WithMany("Comments")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_comments_recipes_recipe_id");

                    b.Navigation("Person");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.RecipeImage", b =>
                {
                    b.HasOne("Domain.Entities.Recipes.Recipe", "Recipe")
                        .WithMany("Images")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_images_recipes_recipe_id");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.RecipeIngredient", b =>
                {
                    b.HasOne("Domain.Entities.Articles.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_ingredients_articles_article_id");

                    b.HasOne("Domain.Entities.Recipes.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_ingredients_recipes_recipe_id");

                    b.HasOne("Domain.Entities.Articles.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_recipe_ingredients_units_unit_id");

                    b.Navigation("Article");

                    b.Navigation("Recipe");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.RecipeRating", b =>
                {
                    b.HasOne("Domain.Entities.People.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_ratings_people_person_id");

                    b.HasOne("Domain.Entities.People.Person", null)
                        .WithMany("RecipeRatings")
                        .HasForeignKey("PersonId1")
                        .HasConstraintName("fk_recipe_ratings_people_person_id1");

                    b.HasOne("Domain.Entities.Recipes.Recipe", "Recipe")
                        .WithMany("Ratings")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_ratings_recipes_recipe_id");

                    b.Navigation("Person");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.RecipeSearchIndex", b =>
                {
                    b.HasOne("Domain.Entities.Recipes.Recipe", "Recipe")
                        .WithOne("SearchIndex")
                        .HasForeignKey("Domain.Entities.Recipes.RecipeSearchIndex", "RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_search_index_recipes_recipe_id");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.RecipeStep", b =>
                {
                    b.HasOne("Domain.Entities.Recipes.Recipe", "Recipe")
                        .WithMany("Steps")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_steps_recipes_recipe_id");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.RecipeTag", b =>
                {
                    b.HasOne("Domain.Entities.Recipes.Recipe", "Recipe")
                        .WithMany("RecipeTags")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_tags_recipes_recipe_id");

                    b.HasOne("Domain.Entities.Recipes.Tag", "Tag")
                        .WithMany("RecipeTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_tags_tags_tag_id");

                    b.Navigation("Recipe");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Domain.Entities.Todos.TodoGroupTodo", b =>
                {
                    b.HasOne("Domain.Entities.Todos.TodoGroup", "TodoGroup")
                        .WithMany("TodoGroupTodos")
                        .HasForeignKey("TodoGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_todo_group_todos_todo_groups_todo_group_id");

                    b.HasOne("Domain.Entities.Todos.Todo", "Todo")
                        .WithOne("TodoGroupTodo")
                        .HasForeignKey("Domain.Entities.Todos.TodoGroupTodo", "TodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_todo_group_todos_todos_todo_id");

                    b.Navigation("Todo");

                    b.Navigation("TodoGroup");
                });

            modelBuilder.Entity("Domain.Entities.Todos.TodoPerson", b =>
                {
                    b.HasOne("Domain.Entities.People.Person", "Person")
                        .WithMany("TodoPeople")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_todo_people_people_person_id");

                    b.HasOne("Domain.Entities.Todos.Todo", "Todo")
                        .WithMany("TodoPeople")
                        .HasForeignKey("TodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_todo_people_todos_todo_id");

                    b.Navigation("Person");

                    b.Navigation("Todo");
                });

            modelBuilder.Entity("Domain.Entities.Articles.Allergen", b =>
                {
                    b.Navigation("ArticleAllergens");
                });

            modelBuilder.Entity("Domain.Entities.Articles.Article", b =>
                {
                    b.Navigation("ArticleAllergens");

                    b.Navigation("ArticleNutrition");

                    b.Navigation("ArticlePrices");
                });

            modelBuilder.Entity("Domain.Entities.Articles.ArticleCategory", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("Children");
                });

            modelBuilder.Entity("Domain.Entities.Articles.Store", b =>
                {
                    b.Navigation("ArticlePrices");
                });

            modelBuilder.Entity("Domain.Entities.Budgets.Budget", b =>
                {
                    b.Navigation("BudgetGroups");
                });

            modelBuilder.Entity("Domain.Entities.Budgets.BudgetGroup", b =>
                {
                    b.Navigation("BudgetRows");
                });

            modelBuilder.Entity("Domain.Entities.Budgets.BudgetRow", b =>
                {
                    b.Navigation("BudgetCells");
                });

            modelBuilder.Entity("Domain.Entities.People.Person", b =>
                {
                    b.Navigation("Budgets");

                    b.Navigation("Favorites");

                    b.Navigation("RecipeComments");

                    b.Navigation("RecipeRatings");

                    b.Navigation("Recipes");

                    b.Navigation("TodoPeople");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Recipe", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Favorites");

                    b.Navigation("Images");

                    b.Navigation("Ingredients");

                    b.Navigation("Ratings");

                    b.Navigation("RecipeCategories");

                    b.Navigation("RecipeTags");

                    b.Navigation("SearchIndex");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Tag", b =>
                {
                    b.Navigation("RecipeTags");
                });

            modelBuilder.Entity("Domain.Entities.Todos.Todo", b =>
                {
                    b.Navigation("TodoGroupTodo");

                    b.Navigation("TodoPeople");
                });

            modelBuilder.Entity("Domain.Entities.Todos.TodoGroup", b =>
                {
                    b.Navigation("TodoGroupTodos");
                });
#pragma warning restore 612, 618
        }
    }
}
