// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations.HomeApp
{
    [DbContext(typeof(HomeAppContext))]
    [Migration("20251109204000_updatedOldTablesToUseSchemas")]
    partial class updatedOldTablesToUseSchemas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Budgets.Budget", b =>
                {
                    b.Property<int>("BudgetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("budget_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BudgetId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("BudgetId")
                        .HasName("pk_budgets");

                    b.HasIndex("PersonId", "Year")
                        .IsUnique()
                        .HasDatabaseName("ix_budgets_person_id_year");

                    b.ToTable("budgets", "budget");
                });

            modelBuilder.Entity("Domain.Entities.Budgets.BudgetCell", b =>
                {
                    b.Property<int>("BudgetCellId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("budget_cell_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BudgetCellId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<int>("BudgetRowId")
                        .HasColumnType("integer")
                        .HasColumnName("budget_row_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("BudgetCellId")
                        .HasName("pk_budget_cells");

                    b.HasIndex("BudgetRowId")
                        .HasDatabaseName("ix_budget_cells_budget_row_id");

                    b.HasIndex("BudgetRowId", "Month")
                        .IsUnique()
                        .HasDatabaseName("ix_budget_cells_budget_row_id_month");

                    b.ToTable("budget_cells", "budget", t =>
                        {
                            t.HasCheckConstraint("ck_budgetcell_month", "month BETWEEN 1 AND 12");
                        });
                });

            modelBuilder.Entity("Domain.Entities.Budgets.BudgetGroup", b =>
                {
                    b.Property<int>("BudgetGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("budget_group_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BudgetGroupId"));

                    b.Property<int>("BudgetGroupType")
                        .HasColumnType("integer")
                        .HasColumnName("budget_group_type");

                    b.Property<int>("BudgetId")
                        .HasColumnType("integer")
                        .HasColumnName("budget_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("BudgetGroupId")
                        .HasName("pk_budget_groups");

                    b.HasIndex("BudgetId")
                        .HasDatabaseName("ix_budget_groups_budget_id");

                    b.HasIndex("BudgetId", "Index")
                        .IsUnique()
                        .HasDatabaseName("ix_budget_groups_budget_id_index");

                    b.ToTable("budget_groups", "budget");
                });

            modelBuilder.Entity("Domain.Entities.Budgets.BudgetRow", b =>
                {
                    b.Property<int>("BudgetRowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("budget_row_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BudgetRowId"));

                    b.Property<int>("BudgetGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("budget_group_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("BudgetRowId")
                        .HasName("pk_budget_rows");

                    b.HasIndex("BudgetGroupId")
                        .HasDatabaseName("ix_budget_rows_budget_group_id");

                    b.HasIndex("BudgetGroupId", "Index")
                        .IsUnique()
                        .HasDatabaseName("ix_budget_rows_budget_group_id_index");

                    b.ToTable("budget_rows", "budget");
                });

            modelBuilder.Entity("Domain.Entities.People.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("person_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PersonId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("username");

                    b.HasKey("PersonId")
                        .HasName("pk_people");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_people_email");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_people_user_id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_people_username");

                    b.ToTable("people", "people");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Core.Favorite", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id")
                        .HasColumnOrder(0);

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(2)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(3);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(4);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(5);

                    b.HasKey("PersonId", "RecipeId")
                        .HasName("pk_favorites");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("ix_favorites_recipe_id");

                    b.ToTable("favorites", "core");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Core.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecipeId"));

                    b.Property<int?>("CookTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("cook_time_minutes");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_public");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int?>("PrepTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("prep_time_minutes");

                    b.Property<decimal?>("Servings")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("servings");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("RecipeId")
                        .HasName("pk_recipes");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_recipes_person_id");

                    b.ToTable("recipes", "core");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Core.RecipeCategory", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id")
                        .HasColumnOrder(0);

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(2)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(3);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(4);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(5);

                    b.HasKey("RecipeId", "CategoryId")
                        .HasName("pk_recipe_categories");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_recipe_categories_category_id");

                    b.ToTable("recipe_categories", "core");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Core.RecipeComment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("comment_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CommentId"));

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comment_text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("CommentId")
                        .HasName("pk_recipe_comments");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_recipe_comments_person_id");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("ix_recipe_comments_recipe_id");

                    b.ToTable("recipe_comments", "core");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Core.RecipeImage", b =>
                {
                    b.Property<int>("RecipeImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("recipe_image_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecipeImageId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("RecipeImageId")
                        .HasName("pk_recipe_images");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("ix_recipe_images_recipe_id");

                    b.ToTable("recipe_images", "core");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Core.RecipeIngredient", b =>
                {
                    b.Property<int>("RecipeIngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("recipe_ingredient_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecipeIngredientId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer")
                        .HasColumnName("ingredient_id");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("note");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("quantity");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("sort_order");

                    b.Property<int?>("UnitId")
                        .HasColumnType("integer")
                        .HasColumnName("unit_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("RecipeIngredientId")
                        .HasName("pk_recipe_ingredients");

                    b.HasIndex("IngredientId")
                        .HasDatabaseName("ix_recipe_ingredients_ingredient_id");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("ix_recipe_ingredients_recipe_id");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_recipe_ingredients_unit_id");

                    b.ToTable("recipe_ingredients", "core");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Core.RecipeRating", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id")
                        .HasColumnOrder(0);

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(2)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("RatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("rated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("Rating")
                        .HasColumnType("smallint")
                        .HasColumnName("rating");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(4);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(5);

                    b.HasKey("RecipeId", "PersonId")
                        .HasName("pk_recipe_ratings");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_recipe_ratings_person_id");

                    b.ToTable("recipe_ratings", "core", t =>
                        {
                            t.HasCheckConstraint("ck_recipe_ratings_rating", "rating BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Core.RecipeStep", b =>
                {
                    b.Property<int>("RecipeStepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("recipe_step_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecipeStepId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instruction");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id");

                    b.Property<int>("StepNumber")
                        .HasColumnType("integer")
                        .HasColumnName("step_number");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("RecipeStepId")
                        .HasName("pk_recipe_steps");

                    b.HasIndex("RecipeId", "StepNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_recipe_steps_recipe_id_step_number");

                    b.ToTable("recipe_steps", "core");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Core.RecipeTag", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id")
                        .HasColumnOrder(0);

                    b.Property<int>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("tag_id")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(2)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(3);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(4);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(5);

                    b.HasKey("RecipeId", "TagId")
                        .HasName("pk_recipe_tags");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_recipe_tags_tag_id");

                    b.ToTable("recipe_tags", "core");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Nutrition.IngredientNutrition", b =>
                {
                    b.Property<int>("IngredientId")
                        .HasColumnType("integer")
                        .HasColumnName("ingredient_id")
                        .HasColumnOrder(0);

                    b.Property<decimal?>("CaloriesKcalPer100g")
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("calories_kcal_per_100g");

                    b.Property<decimal?>("CarbsGPer100g")
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("carbs_g_per_100g");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<decimal?>("FatGPer100g")
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("fat_g_per_100g");

                    b.Property<decimal?>("FiberGPer100g")
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("fiber_g_per_100g");

                    b.Property<string>("LastSource")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_source");

                    b.Property<decimal?>("ProteinGPer100g")
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("protein_g_per_100g");

                    b.Property<decimal?>("SaltGPer100g")
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("salt_g_per_100g");

                    b.Property<decimal?>("SaturatedFatGPer100g")
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("saturated_fat_g_per_100g");

                    b.Property<decimal?>("SugarGPer100g")
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("sugar_g_per_100g");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("IngredientId")
                        .HasName("pk_ingredient_nutrition");

                    b.ToTable("ingredient_nutrition", "nutrition");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Pricing.IngredientPrice", b =>
                {
                    b.Property<int>("IngredientPriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ingredient_price_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IngredientPriceId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("EUR")
                        .HasColumnName("currency");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer")
                        .HasColumnName("ingredient_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<int>("StoreId")
                        .HasColumnType("integer")
                        .HasColumnName("store_id");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer")
                        .HasColumnName("unit_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("ValidFrom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("valid_from")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("IngredientPriceId")
                        .HasName("pk_ingredient_prices");

                    b.HasIndex("StoreId")
                        .HasDatabaseName("ix_ingredient_prices_store_id");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_ingredient_prices_unit_id");

                    b.HasIndex("IngredientId", "StoreId", "ValidFrom", "ValidTo")
                        .HasDatabaseName("ix_ingredient_prices_ingredient_store_valid");

                    b.ToTable("ingredient_prices", "pricing");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Pricing.Store", b =>
                {
                    b.Property<int>("StoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("store_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StoreId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("website_url");

                    b.HasKey("StoreId")
                        .HasName("pk_stores");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_stores_name");

                    b.ToTable("stores", "pricing");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Ref.Allergen", b =>
                {
                    b.Property<int>("AllergenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("allergen_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AllergenId"));

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("AllergenId")
                        .HasName("pk_allergens");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_allergens_name");

                    b.ToTable("allergens", "ref");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Ref.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("category_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("CategoryId")
                        .HasName("pk_categories");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_name");

                    b.ToTable("categories", "ref");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Ref.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ingredient_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IngredientId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<int?>("IngredientCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("ingredient_category_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("IngredientId")
                        .HasName("pk_ingredients");

                    b.HasIndex("IngredientCategoryId")
                        .HasDatabaseName("ix_ingredients_ingredient_category_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_ingredients_name");

                    b.ToTable("ingredients", "ref");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Ref.IngredientAllergen", b =>
                {
                    b.Property<int>("IngredientId")
                        .HasColumnType("integer")
                        .HasColumnName("ingredient_id")
                        .HasColumnOrder(0);

                    b.Property<int>("AllergenId")
                        .HasColumnType("integer")
                        .HasColumnName("allergen_id")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(2)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(3);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(4);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(5);

                    b.HasKey("IngredientId", "AllergenId")
                        .HasName("pk_ingredient_allergens");

                    b.HasIndex("AllergenId")
                        .HasDatabaseName("ix_ingredient_allergens_allergen_id");

                    b.ToTable("ingredient_allergens", "ref");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Ref.IngredientCategory", b =>
                {
                    b.Property<int>("IngredientCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ingredient_category_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IngredientCategoryId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_category_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("IngredientCategoryId")
                        .HasName("pk_ingredient_categories");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_ingredient_categories_name");

                    b.HasIndex("ParentCategoryId")
                        .HasDatabaseName("ix_ingredient_categories_parent_category_id");

                    b.ToTable("ingredient_categories", "ref");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Ref.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tag_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TagId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("TagId")
                        .HasName("pk_tags");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_name");

                    b.ToTable("tags", "ref");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Ref.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("unit_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UnitId"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("abbreviation");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("UnitId")
                        .HasName("pk_units");

                    b.HasIndex("Abbreviation")
                        .IsUnique()
                        .HasDatabaseName("ix_units_abbreviation");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_units_name");

                    b.ToTable("units", "ref");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Search.PopularSearchQuery", b =>
                {
                    b.Property<int>("QueryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("query_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QueryId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("LastSearchedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("last_searched_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("QueryText")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("query_text");

                    b.Property<int>("SearchCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("search_count");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("QueryId")
                        .HasName("pk_popular_search_queries");

                    b.ToTable("popular_search_queries", "search");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Search.RecipeSearchIndex", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id")
                        .HasColumnOrder(0);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("LastIndexedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("last_indexed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("RecipeId")
                        .HasName("pk_recipe_search_index");

                    b.ToTable("recipe_search_index", "search");
                });

            modelBuilder.Entity("Domain.Entities.Todos.Todo", b =>
                {
                    b.Property<int>("TodoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("todo_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TodoId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<bool>("Done")
                        .HasColumnType("boolean")
                        .HasColumnName("done");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("TodoId")
                        .HasName("pk_todos");

                    b.HasIndex("Done")
                        .HasDatabaseName("ix_todos_done");

                    b.HasIndex("Priority")
                        .HasDatabaseName("ix_todos_priority");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_todos_title");

                    b.HasIndex("TodoId")
                        .IsUnique()
                        .HasDatabaseName("ix_todos_todo_id");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_todos_updated_at");

                    b.ToTable("todos", "todo");
                });

            modelBuilder.Entity("Domain.Entities.Todos.TodoGroup", b =>
                {
                    b.Property<int>("TodoGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("todo_group_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TodoGroupId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("TodoGroupId")
                        .HasName("pk_todo_groups");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_todo_groups_title");

                    b.HasIndex("TodoGroupId")
                        .IsUnique()
                        .HasDatabaseName("ix_todo_groups_todo_group_id");

                    b.ToTable("todo_groups", "todo");
                });

            modelBuilder.Entity("Domain.Entities.Todos.TodoGroupTodo", b =>
                {
                    b.Property<int>("TodoGroupTodoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("todo_group_todo_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TodoGroupTodoId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<int>("TodoGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("todo_group_id");

                    b.Property<int>("TodoId")
                        .HasColumnType("integer")
                        .HasColumnName("todo_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("TodoGroupTodoId")
                        .HasName("pk_todo_group_todos");

                    b.HasIndex("TodoGroupId")
                        .HasDatabaseName("ix_todo_group_todos_todo_group_id");

                    b.HasIndex("TodoId")
                        .IsUnique()
                        .HasDatabaseName("ix_todo_group_todos_todo_id");

                    b.ToTable("todo_group_todos", "todo");
                });

            modelBuilder.Entity("Domain.Entities.Todos.TodoPerson", b =>
                {
                    b.Property<int>("TodoPersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("todo_person_id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TodoPersonId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id")
                        .HasColumnOrder(2);

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<int>("TodoId")
                        .HasColumnType("integer")
                        .HasColumnName("todo_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(3);

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id")
                        .HasColumnOrder(4);

                    b.HasKey("TodoPersonId")
                        .HasName("pk_todo_people");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_todo_people_person_id");

                    b.HasIndex("TodoId")
                        .HasDatabaseName("ix_todo_people_todo_id");

                    b.ToTable("todo_people", "todo");
                });

            modelBuilder.Entity("Domain.Entities.Budgets.Budget", b =>
                {
                    b.HasOne("Domain.Entities.People.Person", "Person")
                        .WithMany("Budgets")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_budgets_people_person_id");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Domain.Entities.Budgets.BudgetCell", b =>
                {
                    b.HasOne("Domain.Entities.Budgets.BudgetRow", "BudgetRow")
                        .WithMany("BudgetCells")
                        .HasForeignKey("BudgetRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_budget_cells_budget_rows_budget_row_id");

                    b.Navigation("BudgetRow");
                });

            modelBuilder.Entity("Domain.Entities.Budgets.BudgetGroup", b =>
                {
                    b.HasOne("Domain.Entities.Budgets.Budget", "Budget")
                        .WithMany("BudgetGroups")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_budget_groups_budgets_budget_id");

                    b.Navigation("Budget");
                });

            modelBuilder.Entity("Domain.Entities.Budgets.BudgetRow", b =>
                {
                    b.HasOne("Domain.Entities.Budgets.BudgetGroup", "BudgetGroup")
                        .WithMany("BudgetRows")
                        .HasForeignKey("BudgetGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_budget_rows_budget_groups_budget_group_id");

                    b.Navigation("BudgetGroup");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Core.Favorite", b =>
                {
                    b.HasOne("Domain.Entities.People.Person", "Person")
                        .WithMany("Favorites")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_favorites_people_person_id");

                    b.HasOne("Domain.Entities.Recipes.Core.Recipe", "Recipe")
                        .WithMany("Favorites")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_favorites_recipes_recipe_id");

                    b.Navigation("Person");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Core.Recipe", b =>
                {
                    b.HasOne("Domain.Entities.People.Person", "Person")
                        .WithMany("Recipes")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipes_people_person_id");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Core.RecipeCategory", b =>
                {
                    b.HasOne("Domain.Entities.Recipes.Ref.Category", "Category")
                        .WithMany("RecipeCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_categories_categories_category_id");

                    b.HasOne("Domain.Entities.Recipes.Core.Recipe", "Recipe")
                        .WithMany("RecipeCategories")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_categories_recipes_recipe_id");

                    b.Navigation("Category");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Core.RecipeComment", b =>
                {
                    b.HasOne("Domain.Entities.People.Person", "Person")
                        .WithMany("RecipeComments")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_comments_people_person_id");

                    b.HasOne("Domain.Entities.Recipes.Core.Recipe", "Recipe")
                        .WithMany("Comments")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_comments_recipes_recipe_id");

                    b.Navigation("Person");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Core.RecipeImage", b =>
                {
                    b.HasOne("Domain.Entities.Recipes.Core.Recipe", "Recipe")
                        .WithMany("Images")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_images_recipes_recipe_id");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Core.RecipeIngredient", b =>
                {
                    b.HasOne("Domain.Entities.Recipes.Ref.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_ingredients_ingredients_ingredient_id");

                    b.HasOne("Domain.Entities.Recipes.Core.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_ingredients_recipes_recipe_id");

                    b.HasOne("Domain.Entities.Recipes.Ref.Unit", "Unit")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("UnitId")
                        .HasConstraintName("fk_recipe_ingredients_units_unit_id");

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Core.RecipeRating", b =>
                {
                    b.HasOne("Domain.Entities.People.Person", "Person")
                        .WithMany("RecipeRatings")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_ratings_people_person_id");

                    b.HasOne("Domain.Entities.Recipes.Core.Recipe", "Recipe")
                        .WithMany("Ratings")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_ratings_recipes_recipe_id");

                    b.Navigation("Person");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Core.RecipeStep", b =>
                {
                    b.HasOne("Domain.Entities.Recipes.Core.Recipe", "Recipe")
                        .WithMany("Steps")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_steps_recipes_recipe_id");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Core.RecipeTag", b =>
                {
                    b.HasOne("Domain.Entities.Recipes.Core.Recipe", "Recipe")
                        .WithMany("RecipeTags")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_tags_recipes_recipe_id");

                    b.HasOne("Domain.Entities.Recipes.Ref.Tag", "Tag")
                        .WithMany("RecipeTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_tags_tags_tag_id");

                    b.Navigation("Recipe");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Nutrition.IngredientNutrition", b =>
                {
                    b.HasOne("Domain.Entities.Recipes.Ref.Ingredient", "Ingredient")
                        .WithOne("Nutrition")
                        .HasForeignKey("Domain.Entities.Recipes.Nutrition.IngredientNutrition", "IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ingredient_nutrition_ingredients_ingredient_id");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Pricing.IngredientPrice", b =>
                {
                    b.HasOne("Domain.Entities.Recipes.Ref.Ingredient", "Ingredient")
                        .WithMany("IngredientPrices")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ingredient_prices_ingredients_ingredient_id");

                    b.HasOne("Domain.Entities.Recipes.Pricing.Store", "Store")
                        .WithMany("IngredientPrices")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ingredient_prices_stores_store_id");

                    b.HasOne("Domain.Entities.Recipes.Ref.Unit", "Unit")
                        .WithMany("IngredientPrices")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ingredient_prices_units_unit_id");

                    b.Navigation("Ingredient");

                    b.Navigation("Store");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Ref.Ingredient", b =>
                {
                    b.HasOne("Domain.Entities.Recipes.Ref.IngredientCategory", "Category")
                        .WithMany("Ingredients")
                        .HasForeignKey("IngredientCategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_ingredients_ingredient_categories_ingredient_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Ref.IngredientAllergen", b =>
                {
                    b.HasOne("Domain.Entities.Recipes.Ref.Allergen", "Allergen")
                        .WithMany("IngredientAllergens")
                        .HasForeignKey("AllergenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ingredient_allergens_allergens_allergen_id");

                    b.HasOne("Domain.Entities.Recipes.Ref.Ingredient", "Ingredient")
                        .WithMany("IngredientAllergens")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ingredient_allergens_ingredients_ingredient_id");

                    b.Navigation("Allergen");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Ref.IngredientCategory", b =>
                {
                    b.HasOne("Domain.Entities.Recipes.Ref.IngredientCategory", "ParentCategory")
                        .WithMany("Children")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ingredient_categories_ingredient_categories_parent_category");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Search.RecipeSearchIndex", b =>
                {
                    b.HasOne("Domain.Entities.Recipes.Core.Recipe", "Recipe")
                        .WithOne("SearchIndex")
                        .HasForeignKey("Domain.Entities.Recipes.Search.RecipeSearchIndex", "RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_search_index_recipes_recipe_id");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Domain.Entities.Todos.TodoGroupTodo", b =>
                {
                    b.HasOne("Domain.Entities.Todos.TodoGroup", "TodoGroup")
                        .WithMany("TodoGroupTodos")
                        .HasForeignKey("TodoGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_todo_group_todos_todo_groups_todo_group_id");

                    b.HasOne("Domain.Entities.Todos.Todo", "Todo")
                        .WithOne("TodoGroupTodo")
                        .HasForeignKey("Domain.Entities.Todos.TodoGroupTodo", "TodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_todo_group_todos_todos_todo_id");

                    b.Navigation("Todo");

                    b.Navigation("TodoGroup");
                });

            modelBuilder.Entity("Domain.Entities.Todos.TodoPerson", b =>
                {
                    b.HasOne("Domain.Entities.People.Person", "Person")
                        .WithMany("TodoPeople")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_todo_people_people_person_id");

                    b.HasOne("Domain.Entities.Todos.Todo", "Todo")
                        .WithMany("TodoPeople")
                        .HasForeignKey("TodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_todo_people_todos_todo_id");

                    b.Navigation("Person");

                    b.Navigation("Todo");
                });

            modelBuilder.Entity("Domain.Entities.Budgets.Budget", b =>
                {
                    b.Navigation("BudgetGroups");
                });

            modelBuilder.Entity("Domain.Entities.Budgets.BudgetGroup", b =>
                {
                    b.Navigation("BudgetRows");
                });

            modelBuilder.Entity("Domain.Entities.Budgets.BudgetRow", b =>
                {
                    b.Navigation("BudgetCells");
                });

            modelBuilder.Entity("Domain.Entities.People.Person", b =>
                {
                    b.Navigation("Budgets");

                    b.Navigation("Favorites");

                    b.Navigation("RecipeComments");

                    b.Navigation("RecipeRatings");

                    b.Navigation("Recipes");

                    b.Navigation("TodoPeople");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Core.Recipe", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Favorites");

                    b.Navigation("Images");

                    b.Navigation("Ingredients");

                    b.Navigation("Ratings");

                    b.Navigation("RecipeCategories");

                    b.Navigation("RecipeTags");

                    b.Navigation("SearchIndex");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Pricing.Store", b =>
                {
                    b.Navigation("IngredientPrices");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Ref.Allergen", b =>
                {
                    b.Navigation("IngredientAllergens");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Ref.Category", b =>
                {
                    b.Navigation("RecipeCategories");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Ref.Ingredient", b =>
                {
                    b.Navigation("IngredientAllergens");

                    b.Navigation("IngredientPrices");

                    b.Navigation("Nutrition");

                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Ref.IngredientCategory", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Ref.Tag", b =>
                {
                    b.Navigation("RecipeTags");
                });

            modelBuilder.Entity("Domain.Entities.Recipes.Ref.Unit", b =>
                {
                    b.Navigation("IngredientPrices");

                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("Domain.Entities.Todos.Todo", b =>
                {
                    b.Navigation("TodoGroupTodo");

                    b.Navigation("TodoPeople");
                });

            modelBuilder.Entity("Domain.Entities.Todos.TodoGroup", b =>
                {
                    b.Navigation("TodoGroupTodos");
                });
#pragma warning restore 612, 618
        }
    }
}
