name: .NET CI & Docker

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ "main" ]

env:
  DOTNET_VERSION: "9.0.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Create appsettings.json
      run: |
        echo '{
          "EmailConfiguration": {
            "From": "${{ secrets.EMAIL_FROM }}",
            "SmtpServer": "${{ secrets.SMTP_SERVER }}",
            "Port": "${{ secrets.SMTP_PORT }}",
            "Username": "${{ secrets.SMTP_USERNAME }}",
            "Password": "${{ secrets.SMTP_PASSWORD }}"
          },
          "JwtSettings": {
            "validIssuer": "${{ secrets.JWT_VALID_ISSUER }}",
            "validAudience": "${{ secrets.JWT_VALID_AUDIENCE }}",
            "securityKey": "${{ secrets.JWT_SECURITY_KEY }}",
            "expiryInMinutes": "${{ secrets.JWT_EXPIRY_MINUTES }}"
          },
          "ConnectionStrings": {
            "HomeAppConnection": "${{ secrets.DB_HOMEAPP_CONNECTION }}",
            "HomeAppUserConnection": "${{ secrets.DB_HOMEAPP_USER_CONNECTION }}"
          }
        }' > ./HomeApp.Backend/Web.Api/appsettings.json

    - name: Debug appsettings.json
      run: cat ./HomeApp.Backend/Web.Api/appsettings.json

    - name: Restore dependencies
      run: dotnet restore ./HomeApp.Backend/HomeApp.Backend.sln

    - name: Build
      run: dotnet build ./HomeApp.Backend/HomeApp.Backend.sln --no-restore

    - name: Run All Tests
      run: dotnet test ./HomeApp.Backend/HomeApp.Backend.sln --no-build --verbosity normal

    - name: Prepare Docker tags
      if: github.event_name == 'push'
      id: docker_tags
      run: |
        SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
        REPO_LOWER=$(echo "${GITHUB_ACTOR}" | tr '[:upper:]' '[:lower:]')
        IMAGE="ghcr.io/${REPO_LOWER}/homeapp-backend"
        
        echo "image=${IMAGE}" >> $GITHUB_OUTPUT
        echo "tag_latest=${IMAGE}:latest" >> $GITHUB_OUTPUT
        echo "tag_sha=${IMAGE}:main-${SHORT_SHA}" >> $GITHUB_OUTPUT

        if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
          VERSION_TAG="${GITHUB_REF#refs/tags/}"
          echo "tag_release=${IMAGE}:${VERSION_TAG}" >> $GITHUB_OUTPUT
        fi

    - name: Log in to GitHub Container Registry
      if: github.event_name == 'push'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      if: github.event_name == 'push'
      run: |
        TAG_LATEST="${{ steps.docker_tags.outputs.tag_latest }}"
        TAG_SHA="${{ steps.docker_tags.outputs.tag_sha }}"
        TAG_RELEASE="${{ steps.docker_tags.outputs.tag_release }}"

        docker build \
          -t "$TAG_LATEST" \
          -t "$TAG_SHA" \
          ${TAG_RELEASE:+-t $TAG_RELEASE} \
          -f ./HomeApp.Backend/Web.Api/Dockerfile ./HomeApp.Backend

    - name: Push Docker images
      if: github.event_name == 'push'
      run: |
        docker push ${{ steps.docker_tags.outputs.tag_latest }}
        docker push ${{ steps.docker_tags.outputs.tag_sha }}

        TAG_RELEASE="${{ steps.docker_tags.outputs.tag_release }}"
        if [ -n "$TAG_RELEASE" ]; then
          docker push "$TAG_RELEASE"
        fi

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
