name: .NET CI & Docker

on:
  push:
    branches-ignore:
      - main
  pull_request:
  workflow_run:
    workflows: [".NET CI & Docker"]
    types:
      - completed
  merge_group:
    branches:
      - main

env:
  DOTNET_VERSION: "9.0.x"

jobs:
  build-only:
    if: github.event_name == 'push' && !startsWith(github.ref, 'refs/heads/main')
    runs-on: ubuntu-latest
    name: Build (non-main branches)
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Restore dependencies
        run: dotnet restore ./HomeApp.Backend/HomeApp.Backend.sln
      - name: Build
        run: dotnet build ./HomeApp.Backend/HomeApp.Backend.sln --no-restore

  build-and-test:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    name: Build & Test (PRs)
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Restore dependencies
        run: dotnet restore ./HomeApp.Backend/HomeApp.Backend.sln
      - name: Build
        run: dotnet build ./HomeApp.Backend/HomeApp.Backend.sln --no-restore
      - name: Run All Tests
        run: dotnet test ./HomeApp.Backend/HomeApp.Backend.sln --no-build --verbosity normal

  release-build:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/main') && startsWith(github.event.head_commit.message, 'Merge pull request') && contains(github.event.head_commit.message, 'release/')
    name: Build, Test, Docker & Tag (Release → Main)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ./HomeApp.Backend/HomeApp.Backend.sln
      - name: Build
        run: dotnet build ./HomeApp.Backend/HomeApp.Backend.sln --no-restore
      - name: Run All Tests
        run: dotnet test ./HomeApp.Backend/HomeApp.Backend.sln --no-build --verbosity normal

      - name: Extract Version from Release Branch Name
        id: extract_version
        run: |
          VERSION=$(git log -1 --pretty=%B | grep -oE 'release/v[0-9]+\.[0-9]+\.[0-9]+' | sed 's/release\///')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag ${{ steps.extract_version.outputs.version }}
          git push origin ${{ steps.extract_version.outputs.version }}

      - name: Prepare Docker tags
        id: docker_tags
        run: |
          VERSION=${{ steps.extract_version.outputs.version }}
          IMAGE="ghcr.io/${{ github.repository_owner }}/homeapp-backend"
          echo "image=${IMAGE}" >> $GITHUB_OUTPUT
          echo "tag_latest=${IMAGE}:latest" >> $GITHUB_OUTPUT
          echo "tag_version=${IMAGE}:${VERSION}" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ steps.docker_tags.outputs.tag_latest }} \
            -t ${{ steps.docker_tags.outputs.tag_version }} \
            -f ./HomeApp.Backend/Web.Api/Dockerfile ./HomeApp.Backend

      - name: Push Docker image
        run: |
          docker push ${{ steps.docker_tags.outputs.tag_latest }}
          docker push ${{ steps.docker_tags.outputs.tag_version }}

  create-release:
    name: GitHub Release
    needs: release-build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
