name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env: 
  DOTNET_VERSION: "9.0.x"

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind
        options: --privileged

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Create appsettings.json
      run: |
        echo '{
          "EmailConfiguration": {
            "From": "${{ secrets.EMAIL_FROM }}",
            "SmtpServer": "${{ secrets.SMTP_SERVER }}",
            "Port": "${{ secrets.SMTP_PORT }}",
            "Username": "${{ secrets.SMTP_USERNAME }}",
            "Password": "${{ secrets.SMTP_PASSWORD }}"
          },
          "JwtSettings": {
            "validIssuer": "${{ secrets.JWT_VALID_ISSUER }}",
            "validAudience": "${{ secrets.JWT_VALID_AUDIENCE }}",
            "securityKey": "${{ secrets.JWT_SECURITY_KEY }}",
            "expiryInMinutes": "${{ secrets.JWT_EXPIRY_MINUTES }}"
          },
          "ConnectionStrings": {
            "HomeAppConnection": "${{ secrets.DB_HOMEAPP_CONNECTION }}",
            "HomeAppUserConnection": "${{ secrets.DB_HOMEAPP_USER_CONNECTION }}"
          }
        }' > ./HomeApp.Backend/src/Web.Api/appsettings.json

    - name: Debug appsettings.json
      run: cat ./HomeApp.Backend/src/Web.Api/appsettings.json
        
    - name: Restore dependencies
      run: dotnet restore ./HomeApp.Backend/HomeApp.Backend.sln
      
    - name: Build
      run: dotnet build ./HomeApp.Backend/HomeApp.Backend.sln --no-restore
      
    - name: Run All Tests
      run: dotnet test ./HomeApp.Backend/HomeApp.Backend.sln --no-build --verbosity normal
